### ISSUE TITLE
Some feedbacks and nitpicks

### ISSUE THREAD

**Issue by SHRMP0** [Tiny-Foxes/superuser-outfox#1]
Fonts:
* missing several glyphs, even when language is set to English and transliteration is enabled

Main menu:
* Maybe make the font for the selected button bolder/bigger, sometimes it's not as obvious which one is selected
* Maybe use the new SelectGameMode screen

![2021-08-09_125604](https://user-images.githubusercontent.com/61925574/128737725-c0cf9d58-0357-4dbc-acdb-2756b4e8a068.png)
![2021-08-09_125651](https://user-images.githubusercontent.com/61925574/128737848-739f3b1b-008a-448d-8a86-73d773a15f0e.png)

Music selection screen:
* AutoSetStyle (or whatever it is called) does not work, you will only see singles charts regardless
* Maybe replace the redundant song + artist panels with chart author and chart name/description
* Font sizes vary while scrolling through difficulties (video: https://streamable.com/1avwdv)
* There's no prompt/warning about pressing enter to open the player/song options screen

![2021-08-09_125955](https://user-images.githubusercontent.com/61925574/128737908-179e2a27-84a2-4ac4-9f3c-dd51209f07e9.png)

Evaluation screen:
* Add panels with difficulty, chart author and chart name/description

![2021-08-09_130444](https://user-images.githubusercontent.com/61925574/128737996-98e06814-248b-4696-b2b3-34031b4ad2a6.png)

**Comment by Sudospective** [comment]
Thanks for the feedback! I've got a lot to add for sure, just wasn't sure what it was. As for the fonts, the one I'm using has a lot more than just other language support missing, I'll need to find a new one. Any recommendations?

**Comment by SHRMP0** [comment]
To be honest, I'm not sure on what font to recommend. I do like the [IBM Plex](https://www.ibm.com/plex/) (which also happens to be used on Soundwaves) and [Ubuntu](https://design.ubuntu.com/font/) fonts a lot, but they don't seem to match the aesthetic you're going for

**Comment by Sudospective** [comment]
Going through some of these in more detail, I can elaborate on a few things here:

- Your version may be outdated, check for an update.
- AutoSetStyle isn't implemented at all. The legacy style select has been implemented for now as I figure out how to correctly use AutoSetStyle without having that error you get in the first screenshot. I'll be working on implementing this soon, but as of now, selecting "single" will get you single and only single.
- Song and artist is planned to be moved near the banner, so that it will still be viewable there (so a static position of the song and artist is viewable), but chart name and credit will be put in its original place, as well as chart description for those charts that use it.
- The prompt is something I've been trying to figure out. I'm not exactly sure where it's supposed to go, if it's something that's done through the metrics, or if I need a Lua actor for that, but I'll be implementing this once I know.
- This is due to how I used one BitmapText for all of the notedata details. I never saw an issue with it, but I think it would be good to refactor this to have each detail in its own BitmapText, so this will be done as well.
- Chart difficulty has already been implemented in the evaluation screen in the latest version. However, I will need to add the chart name and credit along with it.
- Making the font bigger for selected text doesn't sound like an appealing solution to me. It _may_ work, but I feel like it'll end up looking like crap. I'll wait for more feedback from others on that one.

These are getting listed in a Trello board so I can organize all the stuff I plan to do with the theme (things like adding scatterplots, NPS graphs, etc.) and again, thank you for the feedback ^-^
